// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxpyG4e1Y7aYSK9aQArRGsbQo0fZzpnc',
    appId: '1:117493804292:web:fa135523c844e1a434b451',
    messagingSenderId: '117493804292',
    projectId: 'medicalapp-ca8ca',
    authDomain: 'medicalapp-ca8ca.firebaseapp.com',
    storageBucket: 'medicalapp-ca8ca.firebasestorage.app',
    measurementId: 'G-L36PQT8LS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZWCkV6IFflEbAYLvmWlSumz0JWjR9M8',
    appId: '1:117493804292:android:4516b1b614bfcb9b34b451',
    messagingSenderId: '117493804292',
    projectId: 'medicalapp-ca8ca',
    storageBucket: 'medicalapp-ca8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeznmAoddlHmEsiixFFnSEx45ZgTU1qiQ',
    appId: '1:117493804292:ios:92b36aa96912cda634b451',
    messagingSenderId: '117493804292',
    projectId: 'medicalapp-ca8ca',
    storageBucket: 'medicalapp-ca8ca.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeznmAoddlHmEsiixFFnSEx45ZgTU1qiQ',
    appId: '1:117493804292:ios:92b36aa96912cda634b451',
    messagingSenderId: '117493804292',
    projectId: 'medicalapp-ca8ca',
    storageBucket: 'medicalapp-ca8ca.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSxpyG4e1Y7aYSK9aQArRGsbQo0fZzpnc',
    appId: '1:117493804292:web:4d0323192989016d34b451',
    messagingSenderId: '117493804292',
    projectId: 'medicalapp-ca8ca',
    authDomain: 'medicalapp-ca8ca.firebaseapp.com',
    storageBucket: 'medicalapp-ca8ca.firebasestorage.app',
    measurementId: 'G-HFDPV9LQDB',
  );

}

////