// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Jw8K9v8W8pQ40rDeGYn9ibghk3lbJuA',
    appId: '1:982572677356:web:226d95c06bf663f3424dc9',
    messagingSenderId: '982572677356',
    projectId: 'medical-app-bfe86',
    authDomain: 'medical-app-bfe86.firebaseapp.com',
    storageBucket: 'medical-app-bfe86.appspot.com',
    measurementId: 'G-5DVSJX5MZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODbgF_6L5PLa2fcWP9aRoGChj0vLZStU',
    appId: '1:982572677356:android:a56a0b42043e24bb424dc9',
    messagingSenderId: '982572677356',
    projectId: 'medical-app-bfe86',
    storageBucket: 'medical-app-bfe86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBt3AkvylGprv_TNWYh5wAmRfFJsJtZwk',
    appId: '1:982572677356:ios:e7022d46a0e39fe6424dc9',
    messagingSenderId: '982572677356',
    projectId: 'medical-app-bfe86',
    storageBucket: 'medical-app-bfe86.appspot.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBt3AkvylGprv_TNWYh5wAmRfFJsJtZwk',
    appId: '1:982572677356:ios:2d07cafc55e759e8424dc9',
    messagingSenderId: '982572677356',
    projectId: 'medical-app-bfe86',
    storageBucket: 'medical-app-bfe86.appspot.com',
    iosBundleId: 'com.example.medicalApp.RunnerTests',
  );
}


////